In [2]:
!pip install numpy 


In [79]:
import numpy as np


In [80]:
l1 = [1,2,3,4,5]
l2 = [[1,2],[1,3],[1,2]]
l3 = [[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]

In [81]:
print(l2[1][1])

3


In [82]:
np.linspace(1,100,5,dtype='i')

array([  1,  25,  50,  75, 100], dtype=int32)

In [83]:
np.ones(shape = (2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [84]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
narr = np.arange(1,101).reshape((10,10))


In [86]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [87]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [88]:
barr = narr[8:10]
barr

array([[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [89]:
barr[:,1:5] = np.arange(1,5).reshape((2,2))

ValueError: could not broadcast input array from shape (2,2) into shape (2,4)

In [90]:
barr


array([[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [91]:
import numpy as nm
import time

l = [i for i in range (10**7)]
start = time.time()


In [92]:
n1 = np.arange(1,21)

In [93]:
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [94]:
np.random.shuffle(n1)
n1

array([ 6, 19,  2,  8,  1, 11, 13, 20,  5, 17,  9,  4,  7, 12,  3, 14, 18,
       15, 16, 10])

In [95]:
n1[1::2]


array([19,  8, 11, 20, 17,  4, 12, 14, 15, 10])

In [96]:
n1[[2,1,4,6,7,4]]



array([ 2, 19,  1, 13, 20,  1])

In [97]:
narr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [98]:
narr[(narr[:,0]-1)%4 == 0]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [99]:
narr[:,narr[0,:]%4 == 0]

array([[ 4,  8],
       [14, 18],
       [24, 28],
       [34, 38],
       [44, 48],
       [54, 58],
       [64, 68],
       [74, 78],
       [84, 88],
       [94, 98]])

In [100]:
n1 = np.arange(1,21).reshape(4,5)


In [101]:
n1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [102]:
np.random.seed(42)
n1 = np.random.randint(1,100,30)
n1

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53,  2, 88,
       30, 38,  2, 64, 60, 21, 33, 76, 58, 22, 89, 49, 91])

In [103]:
n1[(n1>=10) & (n1<=30)]


array([15, 21, 24, 22, 30, 21, 22])

In [104]:
arr = np.arange(1,13).reshape((2,3,2))

In [105]:
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [106]:
for i in range(arr.shape(0)):
    for j in range(arr.shape(1)):
        for k in range(arr.shape(2)):
            print(arr(i,j,k))

TypeError: 'tuple' object is not callable

In [107]:
n1 = np.arange(1,13).reshape(3,4)


In [108]:
n1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
np.array([[10,20,30,40]]) + n1

array([[11, 22, 33, 44],
       [15, 26, 37, 48],
       [19, 30, 41, 52]])

In [115]:
pop = np.loadtxt('populations.txt')
pop

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [136]:
year = pop[:,0]
hare = pop[:,1]
lynx = pop[:,2]
carrot = pop[:,3]


In [135]:
max_hare = hare.max()
year_max_hare = year[hare.argmax()]


In [131]:
max_hare

np.float64(77400.0)

In [132]:
year_max_hare

np.float64(1903.0)

In [133]:
np.mean(pop,axis = 0)

array([ 1910.        , 34080.95238095, 20166.66666667, 42400.        ])

In [137]:
np.mean(pop[:,1:],axis = 1)


array([27433.33333333, 33833.33333333, 40500.        , 50266.66666667,
       45433.33333333, 34033.33333333, 25233.33333333, 25566.66666667,
       24933.33333333, 25533.33333333, 26833.33333333, 31700.        ,
       37700.        , 45666.66666667, 45800.        , 36533.33333333,
       25866.66666667, 21733.33333333, 22533.33333333, 22533.33333333,
       26866.66666667])