numpy basics 

In [2]:
import numpy as np

creating aray from list 

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D array : ", arr_1d)

arr_2d = np.array([[1,2,3] , [4,5,6]])
print("2D array : ", arr_2d)

1D array :  [1 2 3 4 5]
2D array :  [[1 2 3]
 [4 5 6]]


list vs numpy array 

In [4]:
py_list = [1,2,3]
print("python list multiplication" , py_list * 2)

np_array = np.array([1,2,3])
print("python array multiplication" , np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List Operation time : ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2 
print("\n numpy Operation time : ", time.time() - start)

python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]

 List Operation time :  0.05675816535949707

 numpy Operation time :  0.0018129348754882812


Creating array from scratch

In [5]:
zeros = np.zeros((3,4))
print(" zeros array : \n" , zeros)

ones = np.ones((3,4))
print(" ones array : \n" , ones)

full = np.full((2,2) , 7)
print(" full array : \n" , full)

random = np.random.random((3,4))
print(" random array : \n" , random)

sequence = np.arange(0,100)
print(" sequnece array : \n" , sequence)

 zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 ones array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
 full array : 
 [[7 7]
 [7 7]]
 random array : 
 [[0.18855452 0.60670307 0.03733319 0.43348548]
 [0.5723795  0.54609459 0.43274057 0.29051974]
 [0.83848283 0.74848746 0.9074187  0.7091532 ]]
 sequnece array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


vector , Matrix , tensor 

In [6]:
vector = np.array([1,2,3])
print(" vector : \n" , vector)

matrix = np.array([[1,2,3],[1,2,3]])
print(" matrix : \n" , matrix)

tensor = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(" tensor : \n" , tensor)

 vector : 
 [1 2 3]
 matrix : 
 [[1 2 3]
 [1 2 3]]
 tensor : 
 [[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


Array properties

In [7]:
arr = np.array([[1,2,3] , [1,2,3]])
print(" shape : " , arr.shape)
print(" Dimension : " , arr.ndim)
print(" Size : " , arr.size)
print(" dType : " , arr.dtype)

 shape :  (2, 3)
 Dimension :  2
 Size :  6
 dType :  int64


Array reshaping 

In [24]:
arr = np.arange(1,13)
print("\n arr : " , arr)
reshaped  = arr.reshape(3,4)
print("\n reshaped arr : \n" , reshaped )
flattened  = reshaped.flatten()
print("\n flatten array : \n" , flattened )
# ravel (returns view instead of copy 
raveled  = reshaped.ravel()
print("\n raveled array : \n" , raveled )
transpose = reshaped.T
print("\n transposed array : \n" , transpose )


 arr :  [ 1  2  3  4  5  6  7  8  9 10 11 12]

 reshaped arr : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 flatten array : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

 raveled array : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

 transposed array : 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
