Numpy array operations 

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing :" , arr[2:7])
print("with step :",arr[1:8:2])
print("negative indexing :",arr[-3])

Basic slicing : [3 4 5 6 7]
with step : [2 4 6 8]
negative indexing : 7


brr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("specific element  :" , brr[1,2])
print("entire row  :" , brr[0])
print("entire column  :" , brr[:,0])

sorting

In [3]:
unsorted = np.random.randint(1, 21, size = 20)
print(" unsorted :" , unsorted )
print(" sorted :" , np.sort(unsorted))
arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print(" sorted 2d array by row :" , np.sort(arr_2d_unsorted , axis = 0))

 unsorted : [ 2 18  4  5  3  6 16 11  5 18 14 12 16 12 19  6 20 18 15 13]
 sorted : [ 2  3  4  5  5  6  6 11 12 12 13 14 15 16 16 18 18 18 19 20]
 sorted 2d array by row : [[1 1]
 [2 2]
 [3 3]]


filter

In [4]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers%2 ==0]
print(" even numbers  :" , even_numbers )

 even numbers  : [ 2  4  6  8 10]


filter with mask 

In [5]:
mask = numbers > 5
print("numbers greater than 5 : " , numbers[mask])

numbers greater than 5 :  [ 6  7  8  9 10]


fancy indexing vs np.where()

In [6]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where" , numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [7]:
condition_array = np.where(numbers>5 , numbers*4 , numbers)
print(condition_array)
#same as 
#if(numbers>5){
#   numbers*4
#} else {
#   numbers
#}

[ 1  2  3  4  5 24 28 32 36 40]


adding and removing data 


In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
combined_array = np.concatenate((arr1 , arr2))
print(combined_array)

[1 2 3 1 2 3]


array compatibility

In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("compatiblity shapes", a.shape == b.shape)

compatiblity shapes True


In [20]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original , new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original , new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [21]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
deleted

array([1, 2, 4, 5])